application: tiny-quest
version: 1
runtime: python
api_version: 1

handlers:
  
- url: /test.*
  script: gaeunit.py

- url: /static
  static_dir: static

- url: /admin.* 
  script: main.py
  
- url: /api/.* 
  script: main.py

- url: /animationDemo
  static_files: static/SceneGraph.html
  upload: static/SceneGraph.html

- url: /.*
  static_files: static/index.html
  upload: static/index.html
